### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ionelmc** [skippbox/kompose#34]
Latest release (` 0.0.3 (84fa2e0)`) results in this:
```

> kompose k8s convert

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x50f1a4]

goroutine 1 [running]:
github.com/docker/libcompose/project.interpolate.func1(0xc82051edb0, 0x3, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/interpolation.go:155 +0x84
github.com/docker/libcompose/project.parseVariableWithBraces(0xc8204d86c0, 0x24, 0x5, 0xc820326728, 0x0, 0x0, 0x0, 0xc820538230)
        /go/src/github.com/docker/libcompose/project/interpolation.go:54 +0x14c
github.com/docker/libcompose/project.parseInterpolationExpression(0xc8204d86c0, 0x24, 0x1, 0xc820326728, 0x0, 0x0, 0x30, 0x4113b2)
        /go/src/github.com/docker/libcompose/project/interpolation.go:72 +0x9b
github.com/docker/libcompose/project.parseLine(0xc8204d86c0, 0x24, 0xc820326728, 0x0, 0x0, 0x1)
        /go/src/github.com/docker/libcompose/project/interpolation.go:91 +0xbf
github.com/docker/libcompose/project.parseConfig(0xc820502170, 0x7, 0xc8204c9f90, 0x3, 0xc8203264d0, 0xc820326728, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/interpolation.go:111 +0x53a
github.com/docker/libcompose/project.parseConfig(0xc820502170, 0x7, 0xc8204c9f90, 0x3, 0xc8203266a8, 0xc820326728, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/interpolation.go:128 +0x1e3
github.com/docker/libcompose/project.interpolate(0x0, 0x0, 0xc82002e380, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/interpolation.go:154 +0x1be
github.com/docker/libcompose/project.mergeProject(0xc8204f4080, 0xc8204fa000, 0xfb2, 0x11b2, 0xc820326a40, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/merge.go:42 +0x1c3
github.com/docker/libcompose/project.(*Project).Load(0xc8204f4080, 0xc8204fa000, 0xfb2, 0x11b2, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/project.go:127 +0xf6
github.com/docker/libcompose/project.(*Project).Parse(0xc8204f4080, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/project/project.go:73 +0x148
github.com/docker/libcompose/cli/k8s/app.ProjectKuber(0xc8204f4080, 0xc820011080)
        /go/src/github.com/docker/libcompose/cli/k8s/app/commands.go:191 +0x12a
github.com/docker/libcompose/cli/app.WithProject.func1(0xc820011080)
        /go/src/github.com/docker/libcompose/cli/app/app.go:40 +0x154
github.com/docker/libcompose/vendor/github.com/codegangsta/cli.Command.Run(0x14d1c88, 0x7, 0x0, 0x0, 0x16821c0, 0x3a, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/libcompose/vendor/github.com/codegangsta/cli/command.go:113 +0x1082
github.com/docker/libcompose/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8202311e0, 0xc820010f00, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/vendor/github.com/codegangsta/cli/app.go:240 +0xc26
github.com/docker/libcompose/vendor/github.com/codegangsta/cli.Command.startApp(0x14d3930, 0x3, 0x0, 0x0, 0x15c6e00, 0x1c, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/libcompose/vendor/github.com/codegangsta/cli/command.go:155 +0x33d
github.com/docker/libcompose/vendor/github.com/codegangsta/cli.Command.Run(0x14d3930, 0x3, 0x0, 0x0, 0x15c6e00, 0x1c, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/libcompose/vendor/github.com/codegangsta/cli/command.go:40 +0x161e
github.com/docker/libcompose/vendor/github.com/codegangsta/cli.(*App).Run(0xc820230f70, 0xc82000a210, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/docker/libcompose/vendor/github.com/codegangsta/cli/app.go:156 +0xbb1
main.main()
        /go/src/github.com/docker/libcompose/cli/main/main.go:44 +0x169f

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/docker/libcompose/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1cb2f60)
        /go/src/github.com/docker/libcompose/vendor/github.com/golang/glog/glog.go:879 +0x67
created by github.com/docker/libcompose/vendor/github.com/golang/glog.init.1
        /go/src/github.com/docker/libcompose/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 13 [chan send]:
github.com/docker/libcompose/cli/logger.generateColors()
        /go/src/github.com/docker/libcompose/cli/logger/colors.go:27 +0x182
created by github.com/docker/libcompose/cli/logger.init.1
        /go/src/github.com/docker/libcompose/cli/logger/colors.go:33 +0x2b

goroutine 14 [chan receive]:
github.com/docker/libcompose/project.(*defaultListener).start(0xc82037e920)
        /go/src/github.com/docker/libcompose/project/listener.go:47 +0x9e
created by github.com/docker/libcompose/project.NewDefaultListener
        /go/src/github.com/docker/libcompose/project/listener.go:42 +0xb5

goroutine 15 [chan receive]:
github.com/docker/libcompose/project.(*defaultListener).start(0xc8204f8060)
        /go/src/github.com/docker/libcompose/project/listener.go:47 +0x9e
created by github.com/docker/libcompose/project.NewDefaultListener
        /go/src/github.com/docker/libcompose/project/listener.go:42 +0xb5
```

**Comment by ionelmc** [comment]
Input is quite simple:
```
mongo:
    image: mongo:3.2
```

**Comment by runseb** [comment]
@ionelmc can you try `kompose k8s convert`
assuming you named your file docker-compose.yml, it seems to work for me.

which platform are you on ?

**Comment by ionelmc** [comment]
@runseb 64bit ubuntu 14.04

Does the binary depend on certain libraries?

**Comment by ionelmc** [comment]
Maybe you're not testing the same binary? I used https://github.com/skippbox/kompose/releases/download/v0.0.3/kompose_linux-amd64.tar.gz

**Comment by runseb** [comment]
let's copy @ngtuna , probably an issue in the build. OSX works fine.

**Comment by janetkuo** [comment]
The same config works for me too. I'm also running 0.0.3 (84fa2e0) on 64bit ubuntu 14.04.

**Comment by ngtuna** [comment]
Hi @ionelmc,

I tested your given binary on a 64bit ubuntu 14.04 VM and your docker-compose sample. It worked. Can you try on another machine?

```
$ wget https://github.com/skippbox/kompose/releases/download/v0.0.3/kompose_linux-amd64.tar.gz
...
$ cat docker-compose.yml 
mongo:
    image: mongo:3.2

$ ./kompose k8s convert
$ ls -la
total 28224
drwxr-xr-x  2  501 staff     4096 Jun 16 23:02 .
drwx------ 19 root root      4096 Jun 16 22:59 ..
-rw-r--r--  1 root root        28 Jun 16 22:58 docker-compose.yml
-rwxr-xr-x  1  501 staff 28882659 Apr 12 13:49 kompose
-rw-r--r--  1 root root       751 Jun 16 23:02 mongo-rc.json
```

**Comment by ngtuna** [comment]
@ionelmc I'm going to close this issue. In case you still have problem with that, feel free to ping me
